apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python-app
spec:
  selector:
    app: python-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
